# route:
#   # group_by: ["alertname"]
#   # group_wait: 30s
#   # group_interval: 5m
#   # repeat_interval: 1h
#   # receiver: "web.hook"
#   receiver: "telegram"
#   routes:
#     - receiver: "telegram"
#       group_wait: 10s
#       matchers:
#         - severity=~"warning|critical"

# receivers:
#   # - name: "web.hook"
#   #   webhook_configs:
#   #     - url: "http://127.0.0.1:5001/"
#   - name: "telegram"
#     telegram_configs:
#       - bot_token: "7265856018:AAE5roL4ayMWpgGtAnQYhzWLqsCkNuftHo0"
#         chat_id: -1002172090399

# inhibit_rules:
#   - source_match:
#       severity: "critical"
#     target_match:
#       severity: "warning"
#     equal: ["alertname", "dev", "instance"]

global:
  resolve_timeout: 5m

route:
  receiver: "telegram-notifications"

receivers:
  - name: "telegram-notifications"
    telegram_configs:
      - bot_token: "7265856018:AAE5roL4ayMWpgGtAnQYhzWLqsCkNuftHo0"
        chat_id: -1002172090399
        send_resolved: true
        message: "{{ .CommonAnnotations.description }}"
