global:
  resolve_timeout: 5m

route:
  receiver: "telegram-receiver"
  routes:
    - match_re:
        role: "CPU" # Добавляем метку instance_role для сопоставления всех значений
      receiver: "slack-notification"
    - match_re:
        role: "VM"
      receiver: "telegram-receiver"

receivers:
  - name: "telegram-receiver"
    telegram_configs:
      - bot_token: "7265856018:AAE5roL4ayMWpgGtAnQYhzWLqsCkNuftHo0"
        chat_id: -1002172090399
        send_resolved: true
        message: "{{ .CommonAnnotations.description }}"
  - name: 'slack-notification'
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: '#task22'
        send_resolved: true
        text: "{{ .CommonAnnotations.description }}"     
 
