global:
  resolve_timeout: 5m

route:
  receiver: "telegram-receiver"
  routes:
    - match_re:
        alertname: "HighCpuUsage"
        instance_role: ".*"  # Добавляем метку instance_role для сопоставления всех значений
      receiver: "telegram-receiver"


receivers:
  - name: "telegram-receiver"
    telegram_configs:
      - bot_token: "7265856018:AAE5roL4ayMWpgGtAnQYhzWLqsCkNuftHo0"
        chat_id: -1002172090399
        send_resolved: true
        message: "{{ .CommonAnnotations.description }}"

