version: "3.9"

services:
  apache_files:
    image: helistam/apache-task:latest
    container_name: apacheSe
    networks:
      custom_network:
        ipv4_address: 192.30.0.2

  nginx_files:
    image: helistam/task14.3:latest
    ports:
      - "80:80"
    depends_on:
      - apache_files
    container_name: task14.3
    networks:
      custom_network:
        ipv4_address: 192.30.0.3

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.30.0.0/16
