# my global config
global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.30.0.5:9093

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['44.214.118.78:9113']
  - job_name: "ec2_instances"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: "tag:Role"
            values: ["CPU"]
    relabel_configs:
      - source_labels: [_meta_ec2_tag_Role]
        target_label: "role"
        replacement: "CPU"

  - job_name: "ec2_instances_vm"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: "tag:Role"
            values: ["VM"]
    relabel_configs:
      - source_labels: [_meta_ec2_tag_Role]
        target_label: "role"
        replacement: "VM"

  # - job_name: "listen node exporter"
  #   static_configs:
  #     - targets: ["192.30.0.6:9100"]
  #    #new
  # - job_name: "node_exporter_server_1"
  #   static_configs:
  #     - targets: ["3.239.150.93:9100"]
