version: '3.8'

services:
  loki:
    image: grafana/loki:2.7.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    container_name: loki
    volumes:
      - ./loki:/etc/loki
      - ./loki-data:/wal
    networks:
      - custom_network
      

  promtail:
    image: grafana/promtail:2.7.0
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - custom_network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - custom_network

                                                                                                                    
  apache_files:
    image: task22apache:latest
    container_name: apache
    volumes:
      # - /var/log/apache2:/usr/local/apache2/logs
      - /var/log/apache2:/var/log/apache2
    networks:
      custom_network:
        ipv4_address: 192.30.0.8

  nginx_files:
    image: task22nginx:latest
    ports:
      - "80:80"
    depends_on:
      - apache_files
    container_name: nginx
    volumes:
      - /var/log/nginx:/var/log/nginx
    networks:
      custom_network:
        ipv4_address: 192.30.0.9
        
      ### Task 23 ###
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status'
    depends_on:
      - nginx_files
    networks:
      - custom_network
      
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.30.0.0/16


volumes:
  grafana-storage:
