# my global config
global:
  scrape_interval: 10s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.30.0.5:9093

rule_files:
  - /etc/prometheus/alerts.yml
scrape_configs:
  - job_name: "prometheus"

    # static_configs:
    #   - targets: ["localhost:9090"]

  - job_name: "listen node exporter"
    static_configs:
      - targets: ["192.30.0.6:9100"]
